name: Gosec Security Check

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
      go-version:
        required: true
        type: string

jobs:
  security-analysis:
    runs-on:  ${{ inputs.os || 'ubuntu-latest' }}
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Gosec Security Scanner
        run: |
          gosec -fmt=text ./... > gosec-report.txt || true

      - name: Convert Gosec report to Markdown
        run: |
          echo "## Gosec Security Report" > gosec-report.md
          echo "### Issues found:" >> gosec-report.md
          echo '```' >> gosec-report.md
          cat gosec-report.txt >> gosec-report.md
          echo '```' >> gosec-report.md

      - name: Add Gosec report as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: gosec-report.md

    codacy-analysis:
      runs-on: ${{ inputs.os || 'ubuntu-latest' }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go ${{ inputs.go-version }}
          uses: actions/setup-go@v5
          with:
            go-version: ${{ inputs.go-version }}

        - name: Run Codacy Analysis
          uses: codacy/codacy-analysis-cli-action@v4
          with:
            project-token: ${{ secrets.CODACY_API_TOKEN }}
            # Дополнительные опции (раскомментируйте при необходимости):
            # debug: true
            # upload-coverage: true
            # format: cobertura
            # coverage-reports: coverage.xml